### ISSUE TITLE
djvu.org password protected

### ISSUE THREAD

**Issue by bjorn3** [sndjvu/sndjvu.github.io#1]
I am trying to understand what this is a rust implementation of. You are linking to djvu.org multiple times, but it requires a password.

**Comment by cole-miller** [comment]
Hmm, that doesn't happen when I visit http://djvu.org. I don't run that site so I'm afraid I can't give you much help.

DjVu is a document format designed for compact representation of scanned texts. The [Wikipedia article](https://en.wikipedia.org/wiki/DjVu) has good information.

**Comment by bjorn3** [comment]
Yes, that works. Thanks!

**Comment by cole-miller** [comment]
Got it — still not sure what's going on with djvu.org but I'll point all the links to the Sourceforge site instead in case other people have the same problem.
